data_path: "/home/sharon200102/Documents/second degree/Research/microbiome_projects/microbiome/Projects/BGU_fatty_liver/data/data_used/entities_datasets/entities"
xgenerator_internal_layers_structure:
  - 203
  - 100
ygenerator_internal_layers_structure:
  - 68
discriminator_internal_layers_structure:
  - 64
  - 8
projector_internal_layers_structure:
  - 271
  - 100

