authorName: Sharon Komissarov
experimentName: Fatty_liver_GAN_integration_and_batch_discrimination
trialConcurrency: 1
maxExecDuration: 5h
maxTrialNum: 500
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: Random
  # The path and the running command of trial
trial:
  command: python3 /home/sharon200102/Documents/second_degree/Research/integration_tools/GAN_runner.py --c /home/sharon200102/Documents/second_degree/Research/integration_tools/configs/integration_configs/GAN_configs/bgu_fatty_liver/batch_discrimination_and_normalization/params.yaml -n
  codeDir: /home/sharon200102/Documents/second_degree/Research/integration_tools
  gpuNum: 0
