exp_params:
  data_path: "/home/sharon200102/Documents/second_degree/Research/microbiome_projects/microbiome/Projects/GDM/experiment1/data/data_used/entities_datasets/entities"

model_params:
  x_generator_name: "Generator"
  y_generator_name: "Generator"
  discriminator_name: "Discriminator"
  projection_name: "StandardVAE_pl"
  GAN_name: "FMIntegrativeGAN"
  
  x_generator_params:
    layers_structure:
      - 180
      - 100
      - 128
      
    activation_fn: "relu"
    use_batch_norm: True
    
  y_generator_params:
    layers_structure:
      - 180
      - 100
      - 128
    activation_fn: "relu"
    use_batch_norm: True

  discriminator_params:
    layers_structure:
      - 128
      - 64
      - 16
      - 8
      - 2
    activation_fn: "relu"
    use_batch_norm: True
    use_mini_batch_discrimination: True
    layer_index: 2
    similarity_features: 8
    kernel_dims: 8
    feature_matching_layer: 3


  projection_params:
    layers_structure:
      - 360
      - 200
      - 100

  GAN_params:
    xgenerator_optimizer_name: "adam"
    ygenerator_optimizer_name: "adam"
    discriminator_optimizer_name: "adam"
    xgenerator_learning_rate: 0.0006063550977374706
    ygenerator_learning_rate: 0.006196086941931403
    discriminator_learning_rate: 0.005607020540326909
    train_batch_size: 16
 

