exp_params:
  data_path: "/home/sharon200102/Documents/second_degree/Research/microbiome_projects/microbiome/Projects/GDM/experiment1/data/data_used/entities_datasets/entities"
  results_folder: "results/GDM/feature_matching_with_batch_normalization"
  


logger_params:
  GAN_logs_name: "GAN_Logs"
  GAN_checkpoints_name: "GAN_checkpoints"
  manual_seed: 1
  
  
trainer_params:
  max_epochs: 400


model_params:
  x_generator_name: "Generator"
  y_generator_name: "Generator"
  discriminator_name: "Discriminator"
  projection_name: "StandardVAE_pl"
  GAN_name: "FMIntegrativeGAN"
  
  x_generator_params:
    layers_structure:
      - 180
      - 100
      - 128
    activation_fn: "relu"
    use_batch_norm: True
    
  y_generator_params:
    layers_structure:
      - 180
      - 100
      - 128
    activation_fn: "relu"
    use_batch_norm: True


  discriminator_params:
    layers_structure:
      - 128
      - 64
      - 32
      - 8
      - 2
    activation_fn: "relu"
    use_batch_norm: True
    use_mini_batch_discrimination: False
    feature_matching_layer: 3


  projection_params:
    layers_structure:
      - 360
      - 200
      - 100
      - 128

  GAN_params:
    xgenerator_optimizer_name: "adam"
    ygenerator_optimizer_name: "adam"
    discriminator_optimizer_name: "adam"
    xgenerator_learning_rate: 0.0060600205540531586
    ygenerator_learning_rate: 0.0011511316530690343
    discriminator_learning_rate: 0.009422501026680569
    train_batch_size: 64

 

