xgenerator:
  layers_structure:
  - 180
  - 100
  - 128
  activation_fn: "relu"
  use_batch_norm: True

ygenerator:
  layers_structure:
  - 180
  - 100
  - 128
  activation_fn: "relu"
  use_batch_norm: True

discriminator:
  layers_structure:
  - 128
  - 64
  - 32
  - 8
  - 2

  activation_fn: "relu"
  use_batch_norm: True
  use_mini_batch_discrimination: True
  layer_index: 3
  similarity_features: 8
  kernel_dims: 8





